### ISSUE TITLE
Script Review

### ISSUE THREAD

**Issue by Creutzx** [kbrannan/structure-imagery#24]
I finished my first pass through this structure-imagery script. Kevin mentioned we may meet and discuss it next week.

**Comment by BTDangelo** [comment]
Sounds great.

**Comment by kbrannan** [comment]
Take a look at Bernadette's comments
in this file
https://github.com/kbrannan/structure-imagery/blob/1a4180e224f434fed5e935284d2e7e58ea87ac02/structureimagery.py#L1
and this one
https://github.com/kbrannan/structure-imagery/blob/1a4180e224f434fed5e935284d2e7e58ea87ac02/zoom_to_feature_hold.py#L1

**Comment by kbrannan** [comment]
Let me know when you finish looking over Bernadette's comments

**Comment by Creutzx** [comment]
I've looked them over.
