### ISSUE TITLE
Script Comments 

### ISSUE THREAD

**Issue by BTDangelo** [kbrannan/structure-imagery#25]
I went through once and made some comments. There some things that I do not completely understand yet.

**Comment by kbrannan** [comment]
OK, let me know when you are done reviewing

**Comment by BTDangelo** [comment]
I have finished reviewing the "structureimagery" and "zoom_to_feature_hold" scripts.

**Comment by kbrannan** [comment]
Take a look at Brian's comments
https://github.com/kbrannan/structure-imagery/blob/21d3e25fd83938ba69293e9913a216527c55b44c/structureimagery.py#L1

**Comment by kbrannan** [comment]
Let me know when you finish looking over Brian's comments

**Comment by BTDangelo** [comment]
I have gone over Brian's comments.
